### ISSUE TITLE
希望有整合的安装保包

### ISSUE THREAD

**Issue by GANGEN7** [xxiaomuma/kline-douyin#8]
小白运行的不太行，希望可以整合

**Comment by xxiaomuma** [comment]
你可以简单说明一下的需要

**Comment by GANGEN7** [comment]
> 你可以简单说明一下的需要
我这边纯小白，想要在抖音跟小红薯上实现，自动评论，点赞，这个功能，点赞他人评论。这样整体曝光度会提高很多，

**Comment by xxiaomuma** [comment]
你可以联系我 qq2521901773
